[data_args]
datasets = "Milan"
data_path = "data/milano.h5"
num_cells = 100
data_key = "call"
scale = true

[model_args]
pretrained_model_name_or_path = "PatchTST"

[model_args.config]
seq_len = 12
pred_len = 1
e_layers = 3
n_heads = 8
d_model = 128
d_ff = 256
dropout = 0.2
fc_dropout = 0.2
head_dropout = 0.0
individual = false
patch_len = 3
stride = 1
padding_patch = 'end' 
revin = true
affine = false
subtract_last = 0
decomposition = 0
kernel_size = 25
activation = 'gelu'




[training_args]
seed = 42
fp32 = true
output_dir = "outputs/model_output/ST_Linear_Milan_call_12_1/"
num_train_epochs = 50
optim = "adamw_torch"
learning_rate = 1e-4
weight_decay = 0.01
lr_scheduler_type = "cosine"
report_to = "tensorboard"
log_level = "info"
log_level_replica = "warning"
logging_strategy = "steps"
logging_dir = "outputs/tensorboard/ST_Linear_Milan_call_12_1/"
logging_steps = 10
logging_first_step = true
save_strategy = "epoch"
load_best_model_at_end = true
metric_for_best_model = "eval_mse"
greater_is_better = false
save_total_limit = 1
eval_strategy = "epoch"
warmup_ratio = 0.05
eval_on_start = true 
per_device_train_batch_size = 64
per_device_eval_batch_size = 5
dataloader_num_workers = 1
dataloader_pin_memory = false